apiVersion: v1
kind: Service
metadata:
  name: was-service
spec:
  selector:
    app: was
  ports:
    - name: was
      port: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-deployment
  labels:
    app: was
spec:
  replicas: 3
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - name: was
        image: choshsh/spring-petclinic-data-jdbc:latest
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /manage/health/readiness
            port: 8080
          failureThreshold: 3
          periodSeconds: 10
        startupProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 30
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          failureThreshold: 6
          periodSeconds: 10

