apiVersion: v1
kind: Service
metadata:
  name: was-service
spec:
  selector:
    app: was
  ports:
    - name: was
      port: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-deployment
  labels:
    app: was
spec:
  replicas: 3
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - name: was
        image: choshsh/spring-petclinic-data-jdbc:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: log-data
          mountPath: /tmp/logs
        - name: tz-config
          mountPath: /etc/localtime
        readinessProbe:
          httpGet:
            path: /manage/health/readiness
            port: 8080
          failureThreshold: 3
          periodSeconds: 10
        startupProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 30
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          failureThreshold: 6
          periodSeconds: 10

      - name: fluentd
        image: choshsh/fleuntd-elasticsearch
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 24224
        volumeMounts:
        - name: log-data
          mountPath: /tmp/logs
        - name: fluentd-config-volume
          mountPath: /fluentd/etc/
          readOnly: true
          
      volumes:
      - name: log-data
        emptyDir: {}
      - name: fluentd-config-volume
        configMap:
          name: fluentd-config
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Europe/Prague
          type: File      
