apiVersion: v1
kind: Service
metadata:
  name: was-service
spec:
  selector:
    app: was
  ports:
    - name: was
      port: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-deployment
  labels:
    app: was
spec:
  replicas: 3
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - name: was
        image: choshsh/spring-petclinic-data-jdbc:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: log-data
          mountPath: /tmp/logs
        - name: tz-config
          mountPath: /etc/localtime
        readinessProbe:
          httpGet:
            path: /manage/health/readiness
            port: 8080
          failureThreshold: 3
          periodSeconds: 10
        startupProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 30
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          failureThreshold: 6
          periodSeconds: 10

      - name: fluentd
        image: choshsh/fluentd-elasticsearch:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 24224
        volumeMounts:
        - name: log-data
          mountPath: /tmp/logs
        - name: fluentd-config-volume
          mountPath: /fluentd/etc/
          readOnly: true
          
      volumes:
      - name: log-data
        emptyDir: {}
      - name: fluentd-config-volume
        configMap:
          name: fluentd-config
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Europe/Prague
          type: File      
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type tail
      path /tmp/logs/app.log
      pos_file /tmp/logs/app.log.pos
      tag was.log
      <parse>
        @type none
      </parse>
    </source>
    <match **>
      @type copy
      <store>
        @type elasticsearch
        host elasticsearch-svc
        port 9200
        logstash_format true
        logstash_prefix fluentd
        logstash_dateformat %Y%m%d
        include_tag_key true
        type_name was_log
        tag_key @log_name
        flush_interval 1s
      </store>
      <store>
        @type stdout
      </store>
    </match>

