version: "3"

services:
  gradle:
    image: gradle
    user: "gradle:1000"
    volumes:
      - "./:/home/gradle/project"
      - "./.gradle-caches:/home/gradle/.gradle/caches"
    working_dir: "/home/gradle/project"
