version: "3"

services:
  gradle:
    image: choshsh/gradle-did
    #    user: "gradle:1000"
    volumes:
      - "./:/home/gradle/project"
      - "./.gradle-caches:/home/gradle/.gradle/caches"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    working_dir: "/home/gradle/project"
