apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:7.9.3
        imagePullPolicy: IfNotPresent
        env:
        - name: ELASTICSERCH_UTL
          value: "http://elasticsearch-svc:9200"
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch-svc:9200"
        - name: TZ
          value: "Asia/Seoul"
        ports:
        - containerPort: 5601
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: kibana-svc
  namespace: default
spec:
  ports:
  - name: kibana-http
    port: 5601
  selector:
    app: kibana
  type: ClusterIP
